Terence dev
MaxWiesen/telemetry pull request #6
Opened 2024-11-10 21:05 UTC by dumast

Added lap timer + tests
Added lap timer integration to web app (some contain Gray's modifications)
Modified event status in dbhandler to accept a start time
Added macOS dev file

2025-01-19 21:44 UTC, MaxWiesen requested changes
Initial comments on designs--please fix. Overall, very well written. Please also merge new main changes before 2nd round.

2025-01-19 21:44 UTC, MaxWiesen commented on analysis/database/viewer_tool/static/js/decoder.js
> +//TODO remove testing data
Please actually remove

2025-01-19 21:44 UTC, MaxWiesen commented on analysis/database/viewer_tool/static/js/decoder.js
> +    //Pull all relevant on-screen elements to be updated
Cleanup

2025-01-19 21:44 UTC, MaxWiesen commented on analysis/database/viewer_tool/templates/event_tracker.html
> +                console.log("onConnect"); //TODO remove, testing only
Remove

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/lap_timer.py
> +        # points: list[tuple[str, int]] = handler.simple_select(f"SELECT d.gps, p.time FROM dynamics d JOIN packet p ON p.packet_id = d.packet_id WHERE d.packet_id >= {last_packet} ORDER BY d.packet_
Remove

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +    with MQTTHandler(name="terence_dev") as mqtt:
I have a done a bad job of leading by example here, but please change names of MQTT handlers to be significant to the processor/file, instead of devs.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +        #! Will crash if no event
Make this default to -9999 now and remove comment

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +            # if smoothed_torque_request[0] > la_threshold:
Parameterize using fit (add arg to use smoothing). If not used, do everything as normal. If used, just set avg_torque_request = smoothed_torque_request and slightly change the logging accordingly using the flag.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +            # if smoothed_steer_voltage[0] > t_threshold:
Same deal as toque request. Parameterize smoothing.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +                    LIMIT 500
Try to get rid of the unnecessary CTE by rewriting to something like this:
```sql
SELECT 
    d.gps_heading, 
    d.body3_accel, 
    p.time
FROM 
    dynamics d
JOIN 
    packet p 
    ON p.packet_id = d.packet_id
WHERE 
    p.time > {self.current_process.target_time}
    AND p.time <= (
        SELECT MIN(time) 
        FROM packet 
        WHERE time > {self.current_process.target_time}
    )
    AND p.time >= {self.current_process.starting_time}
ORDER BY 
    p.time ASC
LIMIT 500;

```

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +                    logging.info(f"THRESHOLD EXCEEDED")
Delete

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/lap_timer.py
> +        if denominator == 0:
More pythonic to use a `try...except DivideByZero error...` instead of `if denominator == 0` but you don't have to change that if you don't want to.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/tests/Log__2024_10_11__05_50_47.csv
Remove (CSVs do not get saved to GitHub--you can link to them in your test code and throw an error if they aren't downloaded.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier_old.py
Remove file.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/lap_timer.py
> +        requests.post("http://" + os.environ["HOST_IP"] + ":5000/new_lap", data={"time": time})
When using os.environ['key'] you should use a `try...except error` and then do something or raise a detailed error yourself in the except. If you want to have a default behavior (aka it is not critical for the user to have specified something), you can use `os.getenv('key', default)` instead of `os.environ['key']`.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/lap_timer.py
> +    #     """Grabs all the points and does sliding window on here"""
If no longer relevant, delete.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/lap_timer.py
> +        z = R * math.sin(lat_rad)
You need not change it, but note and get comfortable with using np functions always because they are usually faster. If you are already working with np types, np.cos will be faster than np.cos so it is preferable to always use np.

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/lap_timer.py
> +        handler = DBHandler()
Wrap rest of this runner in `with DBHandler(unsafe=True) as handler` to safely create and kill unsafe connection

2025-01-19 21:44 UTC, MaxWiesen commented on stack/processors/lap_timer/tests/paho_testing.py
> +    def add_data_for_gps(self, file: str, delay: float):
Should be integrated into original paho_testing.py as a single routine.

2025-01-26 22:53 UTC, dumast reviewed
Should have fixed most issues

2025-01-26 23:38 UTC, MaxWiesen commented on stack/processors/gps_classifier/gps_classifier.py
> +            points = np.array(DBHandler.simple_select(f"SELECT d.gps_velocity, d.torque_request, c.steer_v, p.time, p.packet_id FROM dynamics d JOIN packet p ON p.packet_id = d.packet_id JOIN control
Extend to multiple lines please.

2025-01-26 23:39 UTC, MaxWiesen approved these changes

2025-01-26 23:39 UTC, merged